name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        cd ..
        git clone https://github.com/aubriaco/solusek
        cd solusek
        cmake src/
        make
    - name: make
      run: |
        export LD_LIBRARY_PATH="../solusek/"
        export CPLUS_INCLUDE_PATH="../solusek/src/include/"
        cmake src/
        make
