name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install libcrypto++-dev -y
        cd ..
        git clone https://github.com/aubriaco/libsolunet
        cd libsolunet
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - name: make
      run: |
        mkdir build/
        cd build/
        cmake ..
        make
    - name: docker
      run: |
        docker build -t solucache
    - name: deploy
      run: |
        docker login docker.pkg.github.com -u aubriaco --password ${{ secrets.GITHUB_TOKEN }}
        docker tag solucache docker.pkg.github.com/aubriaco/solucache/solucache:latest
        docker push docker.pkg.github.com/aubriaco/solucache/solucache:latest
