name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install libcrypto++-dev -y
        cd ..
        git clone https://github.com/aubriaco/solusek
        cd solusek
        mkdir build
        cd build
        cmake ../src/
        make
    - name: make
      run: |
        export LD_LIBRARY_PATH="../solusek/"
        export CPLUS_INCLUDE_PATH="../solusek/src/include/"
        mkdir build/
        cd build/
        cmake ../src
        make
