name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install libcrypto++-dev -y
        cd ..
        git clone https://github.com/aubriaco/libsolunet
        cd libsolunet
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - name: make
      run: |
        mkdir build/
        cd build/
        cmake ..
        make
